const thickness = [
  {
    name: '4/4 Standard Grade',
    thickness_1: '5/4',
    thickness_2: '1',
    db_name: 'STANDARD_GRADE',
    grade_name: '',
    value: 1,
    thickness_values: 1,
  },
  {
    name: '4/4 Select Grade',
    thickness_1: '5/4',
    thickness_2: '1',
    db_name: 'SELECT_GRADE',
    grade_name: 'Select ',
    value: 2,
    thickness_values: 1,
  },
  {
    name: '5/4 Standard Grade',
    thickness_1: '6/4',
    thickness_2: '1 1/8',
    db_name: 'STANDARD_GRADE_THICK',
    grade_name: '',
    value: 3,
    thickness_values: 1.125,
  },
  {
    name: '5/4 Select Grade',
    thickness_1: '6/4',
    thickness_2: '1 1/8',
    db_name: 'SELECT_GRADE_THICK',
    grade_name: 'Select ',
    value: 4,
    thickness_values: 1.125,
  },
  {
    name: '6/4 Standard Grade',
    thickness_1: '8/4',
    thickness_2: '2',
    db_name: 'SIX_QUARTER',
    grade_name: '',
    value: 5,
    thickness_values: 1.5,
  },
  {
    name: '6/4 Select Grade',
    thickness_1: '8/4',
    thickness_2: '2',
    db_name: 'SIX_QUARTER_THICK',
    grade_name: 'Select ',
    value: 4,
    thickness_values: 1.5,
  },
];

export default thickness;
